-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Course"
(
    "Name" character varying,
    "Course_ID" integer NOT NULL,
    describe character varying,
    "Professor_ID" integer NOT NULL,
    PRIMARY KEY ("Course_ID")
);

CREATE TABLE IF NOT EXISTS public."Student"
(
    "Student_Name" character varying,
    "Student_ID" integer,
    "Group" integer,
    PRIMARY KEY ("Student_ID")
);

CREATE TABLE IF NOT EXISTS public."Professor"
(
    "Professor_ID" integer,
    "Professor_Name" character varying,
    PRIMARY KEY ("Professor_ID")
);

CREATE TABLE IF NOT EXISTS public."Registration"
(
    "Registration_ID" integer,
    "Status" character varying,
    "Date" date,
    "Student_ID" integer NOT NULL,
    "Course_ID" integer NOT NULL,
    PRIMARY KEY ("Registration_ID")
);

ALTER TABLE IF EXISTS public."Course"
    ADD FOREIGN KEY ("Professor_ID")
    REFERENCES public."Professor" ("Professor_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Registration"
    ADD FOREIGN KEY ("Student_ID")
    REFERENCES public."Student" ("Student_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Registration"
    ADD FOREIGN KEY ("Course_ID")
    REFERENCES public."Course" ("Course_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;